[package]
name = "chessrw"
version = "0.1.0"
authors = ["Enrico Benedetti <enrico_benedetti@yahoo.com>"]

[dependencies]
strum = "0.10.0"
strum_macros = "0.10.0"
lazy_static = "1.1.0"
clap = "~2.32"
indicatif = "0.9.0"